FROM ubuntu
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN mkdir -p /root/.ssh
ADD {{ id_pub }} /root/.ssh/authorized_keys
RUN chmod -R 700 /root/.ssh
RUN chown -R root:root /root/.ssh
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

